apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fakedestination
  namespace: car-sharing
  labels:
    app: car-sharing
    classification: stub
    role: fake-destination
spec:
  selector:
    matchLabels:
      app: car-sharing
      role: fake-destination
  replicas: 1
  template:
    metadata:
      labels:
        app: car-sharing
        classification: stub
        role: fake-destination
    spec:
      containers:
      - image: host.docker.internal:5000/fakedestination:latest
        name: fakedestination
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        env:
        - name: ConnectionStrings__RabbitMQConnection
          value: "host=host.docker.internal:5672;username=guest;password=_myguest;publisherConfirms=true;timeout=10"